// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwX_inCL98cNiPvHihxyy_V7vO-EsGTBs',
    appId: '1:1072561501064:web:64b30efb308d202a9b003d',
    messagingSenderId: '1072561501064',
    projectId: 'chapterone-ca208',
    authDomain: 'chapterone-ca208.firebaseapp.com',
    storageBucket: 'chapterone-ca208.firebasestorage.app',
    measurementId: 'G-MDKZ6B9FMB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEDkUeu2ghR_wOUkupjRh_w_vlhZ3IXKY',
    appId: '1:1072561501064:android:022fca4794579e379b003d',
    messagingSenderId: '1072561501064',
    projectId: 'chapterone-ca208',
    storageBucket: 'chapterone-ca208.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7HNn9vKnUeoXICEaB2R-_wqDNtMJZZLA',
    appId: '1:1072561501064:ios:e738b1f9513314749b003d',
    messagingSenderId: '1072561501064',
    projectId: 'chapterone-ca208',
    storageBucket: 'chapterone-ca208.firebasestorage.app',
    iosBundleId: 'com.bazookalabs.chapterone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwX_inCL98cNiPvHihxyy_V7vO-EsGTBs',
    appId: '1:1072561501064:web:2725ed55a2c708f49b003d',
    messagingSenderId: '1072561501064',
    projectId: 'chapterone-ca208',
    authDomain: 'chapterone-ca208.firebaseapp.com',
    storageBucket: 'chapterone-ca208.firebasestorage.app',
    measurementId: 'G-SR403VY7CN',
  );
}
